runtime: python37
service: marta-bff

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: https://marta-tech.firebaseapp.com

#   # This handler routes all requests not caught above to your main app. It is
#   # required when static routes are defined, but can be omitted (along with
#   # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
